### ISSUE TITLE
Turn into a CLI

### ISSUE THREAD

**Issue by brunoborges** [petarov/java-app-icons#1]
Next thing is to turn this into a CLI.

Good opportunity to learn GraalVM!

**Comment by petarov** [comment]
Not a bad idea! 🙂

**Comment by petarov** [comment]
Done - [java-app-icons-bin](https://github.com/petarov/java-app-icons-bin).

Thanks for suggesting. I wanted to try GraalVM's Native Image for a long time now. 😉
